# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topo_graph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='topo_graph.proto',
  package='cloud.navi',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10topo_graph.proto\x12\ncloud.navi\"\xd8\x01\n\x08TopoNode\x12\x0f\n\x07lane_id\x18\x01 \x01(\x04\x12\x0e\n\x06length\x18\x02 \x01(\x01\x12\x16\n\x0e\x61nchor_point_x\x18\x03 \x01(\x01\x12\x16\n\x0e\x61nchor_point_y\x18\x04 \x01(\x01\x12\x16\n\x0epredecessor_id\x18\x05 \x03(\x04\x12\x14\n\x0csuccessor_id\x18\x06 \x03(\x04\x12%\n\x1dleft_neighbor_forward_lane_id\x18\x07 \x03(\x04\x12&\n\x1eright_neighbor_forward_lane_id\x18\x08 \x03(\x04\"\xf2\x02\n\x08TopoEdge\x12\x0f\n\x07\x65\x64ge_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x66rom_lane_id\x18\x02 \x01(\x04\x12\x12\n\nto_lane_id\x18\x03 \x01(\x04\x12\x30\n\tconn_type\x18\x04 \x01(\x0e\x32\x1d.cloud.navi.TopoEdge.ConnType\"\xf8\x01\n\x08\x43onnType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x12\x15\n\x11LANE_CHANGE_RIGHT\x10\x02\x12\x14\n\x10LANE_CHANGE_LEFT\x10\x03\x12\x13\n\x0fJUNC_TRUN_RIGHT\x10\x04\x12\x12\n\x0eJUNC_TURN_LEFT\x10\x05\x12\x10\n\x0cJUNC_FORWARD\x10\x06\x12\x0f\n\x0bJUNC_U_TURN\x10\x07\x12\x13\n\x0fLANE_LFET_MERGE\x10\x08\x12\x14\n\x10LANE_RIGHT_MERGE\x10\t\x12\x13\n\x0fLANE_LFET_SPLIT\x10\n\x12\x14\n\x10LANE_RIGHT_SPLIT\x10\x0b\"\x88\x01\n\x10TopoNodeEdgePair\x12\"\n\x04node\x18\x01 \x01(\x0b\x32\x14.cloud.navi.TopoNode\x12\'\n\tpre_edges\x18\x02 \x03(\x0b\x32\x14.cloud.navi.TopoEdge\x12\'\n\tsuc_edges\x18\x03 \x03(\x0b\x32\x14.cloud.navi.TopoEdge\"\x86\x01\n\tTopoGraph\x12\x12\n\ngraph_name\x18\x01 \x01(\t\x12\x19\n\x11graph_description\x18\x02 \x01(\t\x12\x15\n\rgraph_version\x18\x03 \x01(\t\x12\x33\n\rmap_node_edge\x18\x04 \x03(\x0b\x32\x1c.cloud.navi.TopoNodeEdgePair'
)



_TOPOEDGE_CONNTYPE = _descriptor.EnumDescriptor(
  name='ConnType',
  full_name='cloud.navi.TopoEdge.ConnType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LANE_CHANGE_RIGHT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LANE_CHANGE_LEFT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JUNC_TRUN_RIGHT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JUNC_TURN_LEFT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JUNC_FORWARD', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JUNC_U_TURN', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LANE_LFET_MERGE', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LANE_RIGHT_MERGE', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LANE_LFET_SPLIT', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LANE_RIGHT_SPLIT', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=374,
  serialized_end=622,
)
_sym_db.RegisterEnumDescriptor(_TOPOEDGE_CONNTYPE)


_TOPONODE = _descriptor.Descriptor(
  name='TopoNode',
  full_name='cloud.navi.TopoNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lane_id', full_name='cloud.navi.TopoNode.lane_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='cloud.navi.TopoNode.length', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anchor_point_x', full_name='cloud.navi.TopoNode.anchor_point_x', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anchor_point_y', full_name='cloud.navi.TopoNode.anchor_point_y', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predecessor_id', full_name='cloud.navi.TopoNode.predecessor_id', index=4,
      number=5, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='successor_id', full_name='cloud.navi.TopoNode.successor_id', index=5,
      number=6, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_neighbor_forward_lane_id', full_name='cloud.navi.TopoNode.left_neighbor_forward_lane_id', index=6,
      number=7, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_neighbor_forward_lane_id', full_name='cloud.navi.TopoNode.right_neighbor_forward_lane_id', index=7,
      number=8, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=249,
)


_TOPOEDGE = _descriptor.Descriptor(
  name='TopoEdge',
  full_name='cloud.navi.TopoEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='edge_id', full_name='cloud.navi.TopoEdge.edge_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_lane_id', full_name='cloud.navi.TopoEdge.from_lane_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_lane_id', full_name='cloud.navi.TopoEdge.to_lane_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conn_type', full_name='cloud.navi.TopoEdge.conn_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TOPOEDGE_CONNTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=622,
)


_TOPONODEEDGEPAIR = _descriptor.Descriptor(
  name='TopoNodeEdgePair',
  full_name='cloud.navi.TopoNodeEdgePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='cloud.navi.TopoNodeEdgePair.node', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre_edges', full_name='cloud.navi.TopoNodeEdgePair.pre_edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='suc_edges', full_name='cloud.navi.TopoNodeEdgePair.suc_edges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=761,
)


_TOPOGRAPH = _descriptor.Descriptor(
  name='TopoGraph',
  full_name='cloud.navi.TopoGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph_name', full_name='cloud.navi.TopoGraph.graph_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graph_description', full_name='cloud.navi.TopoGraph.graph_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graph_version', full_name='cloud.navi.TopoGraph.graph_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_node_edge', full_name='cloud.navi.TopoGraph.map_node_edge', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=764,
  serialized_end=898,
)

_TOPOEDGE.fields_by_name['conn_type'].enum_type = _TOPOEDGE_CONNTYPE
_TOPOEDGE_CONNTYPE.containing_type = _TOPOEDGE
_TOPONODEEDGEPAIR.fields_by_name['node'].message_type = _TOPONODE
_TOPONODEEDGEPAIR.fields_by_name['pre_edges'].message_type = _TOPOEDGE
_TOPONODEEDGEPAIR.fields_by_name['suc_edges'].message_type = _TOPOEDGE
_TOPOGRAPH.fields_by_name['map_node_edge'].message_type = _TOPONODEEDGEPAIR
DESCRIPTOR.message_types_by_name['TopoNode'] = _TOPONODE
DESCRIPTOR.message_types_by_name['TopoEdge'] = _TOPOEDGE
DESCRIPTOR.message_types_by_name['TopoNodeEdgePair'] = _TOPONODEEDGEPAIR
DESCRIPTOR.message_types_by_name['TopoGraph'] = _TOPOGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopoNode = _reflection.GeneratedProtocolMessageType('TopoNode', (_message.Message,), {
  'DESCRIPTOR' : _TOPONODE,
  '__module__' : 'topo_graph_pb2'
  # @@protoc_insertion_point(class_scope:cloud.navi.TopoNode)
  })
_sym_db.RegisterMessage(TopoNode)

TopoEdge = _reflection.GeneratedProtocolMessageType('TopoEdge', (_message.Message,), {
  'DESCRIPTOR' : _TOPOEDGE,
  '__module__' : 'topo_graph_pb2'
  # @@protoc_insertion_point(class_scope:cloud.navi.TopoEdge)
  })
_sym_db.RegisterMessage(TopoEdge)

TopoNodeEdgePair = _reflection.GeneratedProtocolMessageType('TopoNodeEdgePair', (_message.Message,), {
  'DESCRIPTOR' : _TOPONODEEDGEPAIR,
  '__module__' : 'topo_graph_pb2'
  # @@protoc_insertion_point(class_scope:cloud.navi.TopoNodeEdgePair)
  })
_sym_db.RegisterMessage(TopoNodeEdgePair)

TopoGraph = _reflection.GeneratedProtocolMessageType('TopoGraph', (_message.Message,), {
  'DESCRIPTOR' : _TOPOGRAPH,
  '__module__' : 'topo_graph_pb2'
  # @@protoc_insertion_point(class_scope:cloud.navi.TopoGraph)
  })
_sym_db.RegisterMessage(TopoGraph)


# @@protoc_insertion_point(module_scope)
